[package]
name = "rust_tests"
version = "0.1.0"
authors = []
edition = "2021"

[profile.dev]
panic = "abort"

[dependencies]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort" 
strip = "symbols"
