[package]
name = "host_cairo"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
riscairo = { git = "https://github.com/massalabs/riscairo.git" }

[lib]
sierra = true        # Enable Sierra codegen.
casm = true         # Enable CASM codegen.
sierra-text = false  # Enable textual Sierra codegen.
